name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'gradle/**'
      - '*.gradle'
  workflow_dispatch:
    inputs:
      package:
          type: string
          description: "Package ID"
          required: true
          default: ""
      app_name:
          type: string
          description: "Appli name"
          required: false
          default: ""
      stub:
          type: boolean
          description: "Stub mode (versionCode: 1)"
          required: true
          default: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build with Gradle
        run: |
          # Set package ID
          sed -i -e "s/com.android.vending/${{ inputs.package }}/g" app/build.gradle
          # Stub or Install block
          if [ "${{ inputs.stub }}" == "true" ]; then
            sed -i -e 's/2147483647/1/g' app/build.gradle
          fi
          echo "version=$(grep versionCode app/build.gradle | awk '{print $2}')" >> $GITHUB_ENV
          # Set app name
          if [ "${{ inputs.app_name }}" != "" ]; then
            sed -i -e 's/\ \/>//g' app/src/main/AndroidManifest.xml
            sed -i -e "/application/a \        android:label=\"${{ inputs.app_name }}\"\ \/>" app/src/main/AndroidManifest.xml
          fi
          # Build
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package }}_${{ env.version }}
          path: app/build/outputs/apk/release/app-release.apk
